Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "racoon63/centos7"

    node1.vm.provider "virtualbox" do |v|
      v.name = "dev-node1"
      v.memory = 2048
      v.cpus = 2
      v.customize ["modifyvm", :id, "--audio", "none"]
    end

    node1.vm.hostname = "node1"

    node1.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"
    node1.vm.provision :shell, path: "bootstrap.sh"

    node1.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_ed25519"]
    node1.ssh.insert_key = false
    node1.ssh.keep_alive = true

    node1.vm.network "private_network", ip: "192.168.5.10", :name => 'vboxnet1', :adapter => 3
    node1.vm.network "private_network", ip: "10.10.10.10", virtualbox__intnet: "dev-net"
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "racoon63/centos7"

    node2.vm.provider "virtualbox" do |v|
      v.name = "dev-node2"
      v.memory = 2048
      v.cpus = 2
      v.customize ["modifyvm", :id, "--audio", "none"]
    end

    node2.vm.hostname = "node2"

    node2.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"
    node2.vm.provision :shell, path: "bootstrap.sh"

    node2.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_ed25519"]
    node2.ssh.insert_key = false
    node2.ssh.keep_alive = true

    node2.vm.network "private_network", ip: "192.168.5.20", :name => 'vboxnet1', :adapter => 3
    node2.vm.network "private_network", ip: "10.10.10.20", virtualbox__intnet: "dev-net"
  end
end