Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "my-vm"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.box = "hashicorp/bionic64"
  
  config.vm.hostname = "ubuntu-18.04-test"

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision :shell, path: "bootstrap.sh"
  
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
  config.ssh.insert_key = false
  config.ssh.keep_alive = true
  
  config.vm.network "private_network", ip: "192.168.0.10", :name => 'vboxnet1', :adapter => 3
  config.vm.network "private_network", ip: "10.100.0.10", virtualbox__intnet: "my_test_network"
  
end
