Vagrant.configure("2") do |config|

  config.vm.define "centos-7-template" do |web|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
      v.name = "centos-7-template"
      v.memory = 2048
      v.cpus = 2
      v.vm.disk :disk, size: "100GB", primary: true
      v.customize ["modifyvm", :id, "--audio", "none"]
    end

    config.vm.hostname = "centos-7-template"

    config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"
    config.vm.provision :shell, path: "bootstrap.sh"

    config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_ed25519"]
    config.ssh.insert_key = false
    config.ssh.keep_alive = true

    # Add vm to the first adapter default nat-network (https://www.vagrantup.com/docs/virtualbox/boxes.html#virtual-machine)
    #config.vm.network "private_network", ip: "192.168.5.10", :name => 'vboxnet1', :adapter => 3
    # Add vm to custom network
    # config.vm.network "private_network", ip: "10.100.1.2", virtualbox__intnet: "My_Test_Network"
  end
end