Vagrant.configure("2") do |config|

  config.vm.define "my-vm" do |web|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
      v.name = "centos-7-test"
      v.memory = 2048
      v.cpus = 2
      v.customize ["modifyvm", :id, "--audio", "none"]
    end

    config.vm.hostname = "testvm"

    config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"
    config.vm.provision :shell, path: "bootstrap.sh"

    config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_ed25519"]
    config.ssh.insert_key = false
    config.ssh.keep_alive = true

    config.vm.network "private_network", ip: "192.168.1.2", :name => 'vboxnet1', :adapter => 3
    config.vm.network "private_network", ip: "10.100.1.2", virtualbox__intnet: "My_Test_Network"
  end
end